---
- name: Install prerequisites for OMS Agent
  package:
    name: python-ctypes
    state: present

- name: Check whether OMS agent is already installed
  stat:
    path: "{{ oms_agent_path }}"
  register: oms_agent_installed

- name: Install OMS agent
  when: not oms_agent_installed.stat.exists
  block:
    - name: Download OMS agent
      get_url:
        url: "{{ url_omsagent }}"
        dest: /tmp/
        mode: 0755

    - name: Install OMS agent
      command: /tmp/onboard_agent.sh

    - name: Install deamon
      command: "/opt/microsoft/omsagent/bin/service_control restart {{ workspace_id }}"

    - name: Remove OMS agent installer
      file: path=/tmp/onboard_agent.sh state=absent

    # Fix to address issue with oms agent and container monitoring, see:
    # https://github.com/Microsoft/OMS-docker/blob/master/ReleaseNote.md#due-to-the-backend-changes-for-container-monitoring-with-oms-agent-for-linux-and-it-is-a-fresh-install-you-will-need-to-run-this-workaround
    # only required on first-time setups
    - name: Re-onboard OMS Agent workspace to workaround issue https://bit.ly/2t2aNCB
      block:
        - name: Remove all workspaces
          command: "{{ oms_agent_path }} -X"
        - name: Re-onboard workspace
          command: "{{ oms_agent_path }} -w {{ workspace_id }} -s {{ workspace_key }}"
