---
- name: Install prerequisites for OMS Agent
  package:
    name: python-ctypes
    state: present

- name: Install OMS Agent using existing role
  import_role: svendewindt.omsagentlinux

# Fix to address issue with oms agent and container monitoring, see:
# https://github.com/Microsoft/OMS-docker/blob/master/ReleaseNote.md#due-to-the-backend-changes-for-container-monitoring-with-oms-agent-for-linux-and-it-is-a-fresh-install-you-will-need-to-run-this-workaround
# only required on first-time setups
- name: Re-onboard OMS Agent workspace to workaround issue https://bit.ly/2t2aNCB
  when: not oms_agent_installed.stat.exists
  block:
    - name: Remove all workspaces
      command: "{{ oms_agent_path }} -X"
    - name: Re-onboard workspace
      command: "{{ oms_agent_path }} -w {{ workspace_id }} -s {{ workspace_key }}"
